# Generated by Django 2.2.6 on 2019-10-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityhistory',
            name='realized_volatility',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='securityhistory',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='QuarterReturn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end_date', models.DateField()),
                ('data_end_date', models.DateField()),
                ('quad', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quarter_return', models.FloatField()),
            ],
            options={
                'unique_together': {('quarter_end_date', 'data_end_date', 'quad')},
            },
        ),
    ]
