# Generated by Django 2.2.6 on 2019-10-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0003_auto_20191016_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterreturn',
            name='label',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='quarterreturn',
            unique_together={('quarter_end_date', 'data_end_date', 'label')},
        ),
        migrations.RemoveField(
            model_name='quarterreturn',
            name='quad',
        ),
    ]
