# Generated by Django 2.2.6 on 2019-10-19 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0004_auto_20191016_2051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SecurityHistory',
            new_name='YahooHistory',
        ),
    ]
