# Generated by Django 2.2.6 on 2019-10-26 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0006_alphavantagehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuadForecasts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end_date', models.DateField()),
                ('date', models.DateField()),
                ('cpi_roc', models.FloatField()),
                ('gdp_roc', models.FloatField()),
                ('quad', models.IntegerField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('quarter_end_date', 'date')},
            },
        ),
    ]
