# Generated by Django 2.2.6 on 2019-11-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0008_auto_20191111_2021'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuarterReturn',
            new_name='QuadReturn',
        ),
    ]
