# Generated by Django 2.2.6 on 2020-04-25 22:26

from django.db import migrations, models

def forwards_func(apps, schema_editor):
    QuadReturn = apps.get_model("DataAcquisition", "QuadReturn")
    QuadReturn.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0011_auto_20200323_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadreturn',
            name='quad_stdev',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.RunPython(forwards_func)
    ]
