# Generated by Django 2.2.6 on 2020-04-25 23:21

from django.db import migrations

def forwards_func(apps, schema_editor):
    QuadReturn = apps.get_model("DataAcquisition", "QuadReturn")
    QuadReturn.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0012_quadreturn_quad_stdev'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
