# Generated by Django 2.2.6 on 2020-05-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0013_auto_20200425_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitmentOfTraders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.TextField()),
                ('date', models.DateField()),
                ('one_year_z', models.FloatField()),
                ('three_year_z', models.FloatField()),
            ],
            options={
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
