# Generated by Django 2.2.6 on 2020-05-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0014_commitmentoftraders'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentoftraders',
            name='one_year_abs_z',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commitmentoftraders',
            name='three_year_abs_z',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
