# Generated by Django 2.2.6 on 2020-05-21 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0015_auto_20200520_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='commitmentoftraders',
            name='net_long',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
