# Generated by Django 2.2.6 on 2020-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0016_commitmentoftraders_net_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='yahoohistory',
            name='realized_volatility_week',
            field=models.FloatField(null=True),
        ),
    ]
