# Generated by Django 2.2.13 on 2020-12-05 00:28

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0018_remove_yahoohistory_realized_volatility_week'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop)
    ]
