# Generated by Django 2.2.13 on 2021-01-15 15:52

from django.db import migrations

def forwards_func(apps, schema_editor):
    QuadReturn = apps.get_model("DataAcquisition", "QuadReturn")
    
    for obj in QuadReturn.objects.all():
        obj.label = "YahooHistory_" + obj.label
        obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0020_alphavantagehistory_realized_volatility'),
    ]

    operations = [
        migrations.RunPython(forwards_func)
    ]
