# Generated by Django 2.2.13 on 2021-03-27 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0022_bitfinexhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commitmentoftraders',
            name='one_year_abs_z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='commitmentoftraders',
            name='one_year_z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='commitmentoftraders',
            name='three_year_abs_z',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='commitmentoftraders',
            name='three_year_z',
            field=models.FloatField(null=True),
        ),
    ]
