# Generated by Django 2.2.13 on 2021-04-19 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0023_auto_20210326_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinGeckoPair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(help_text='The contract address of the token represented by this symbol', unique=True)),
                ('coin_id', models.TextField(blank=True, help_text='The CoinGecko ID for this token')),
                ('ticker', models.TextField(help_text='Descriptive ticker, used for display only')),
                ('counter_currency', models.TextField(default='eth', help_text='Currency to return prices relative to')),
            ],
        ),
        migrations.CreateModel(
            name='CoinGeckoHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ticker', models.CharField(max_length=12)),
                ('close_price', models.FloatField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('realized_volatility', models.FloatField(null=True)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataAcquisition.CoinGeckoPair')),
            ],
            options={
                'unique_together': {('pair', 'date')},
            },
        ),
    ]
