# Generated by Django 2.2.24 on 2021-10-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0024_coingeckohistory_coingeckopair'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDPForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter_end_date', models.DateField()),
                ('date', models.DateField()),
                ('gdp', models.FloatField()),
            ],
        ),
    ]
