# Generated by Django 3.2 on 2022-10-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0026_delete_alphavantagehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoinGeckoHistory',
        ),
        migrations.DeleteModel(
            name='CoinGeckoPair',
        ),
    ]
