# Generated by Django 3.2.16 on 2022-10-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0027_auto_20221015_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignalTimeSeries',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('run_time', models.DateTimeField()),
                ('analysis_label', models.TextField()),
                ('ticker', models.TextField(null=True)),
                ('signal', models.FloatField(null=True)),
                ('target_date', models.DateField()),
            ],
            options={
                'db_table': 'signal_time_series',
                'managed': False,
            },
        ),
    ]
