# Generated by Django 3.2.21 on 2025-05-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0030_lengthen_yahoohistory_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadreturn',
            name='linear_eoq_forecast',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quadreturn',
            name='linear_eoq_r2',
            field=models.FloatField(null=True),
        ),
    ]
