# Generated by Django 3.2.21 on 2025-05-17 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0031_calculated_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadreturn',
            name='linear_eoq_95pct',
            field=models.FloatField(null=True),
        ),
    ]
