# Generated by Django 3.2.21 on 2025-05-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataAcquisition', '0032_quadreturn_linear_eoq_95pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quadforecasts',
            name='cpi_origin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quadforecasts',
            name='cpi_sigma',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quadforecasts',
            name='gdp_origin',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='quadforecasts',
            name='gdp_sigma',
            field=models.FloatField(null=True),
        ),
    ]
